name: VS

on: workflow_dispatch

jobs:
  ci:
    name: windows
    runs-on: windows-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: Configure
      run: |
        cmake -G "Visual Studio 17 2025" -A x64 -B build
    - name: Build Debug
      run: cmake --build build --config Debug --verbose
    - name: Build Release
      run: cmake --build build --config Release --verbose
